# Generated by Django 5.1 on 2024-08-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nameOrig', models.CharField(max_length=255)),
                ('oldbalanceOrg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('newbalanceOrig', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oldbalanceDest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('newbalanceDest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ac_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('recipient_name', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('payment', 'Payment'), ('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], max_length=20)),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_fraud', models.BooleanField(default=False)),
                ('isFlaggedFraud', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
            ],
        ),
    ]
