# Generated by Django 5.1 on 2024-08-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
